### ISSUE TITLE
Sub menu not displayed completly

### ISSUE THREAD

**Issue by mctdi** [vsn4ik/bootstrap-submenu#37]
i try without success to display a submenu

i put a button action on top of a bootstrap-table
Payer submenu is not displayed

![submenu_issue](https://cloud.githubusercontent.com/assets/15982302/15445968/c32083d8-1edc-11e6-96a4-b669a242415e.png)

i created an example
http://jsfiddle.net/r9o45y0k/

**Comment by vsn4ik** [comment]
@mctdi, thx for report and for example link. Use:
```css
.fixed-table-toolbar .dropdown-menu {
  overflow: visible;
}
```
or create issue for bootstrap-table project.
