### ISSUE TITLE
Unable to compile bootstrap-submenu.less file when importing bootstrap-submenu with Composer

### ISSUE THREAD

**Issue by ninsuo** [vsn4ik/bootstrap-submenu#5]
I tried to build bootstrap-submenu.less using Symfony2 assetics, but the file begins with:

```less
@import "../node_modules/bootstrap/less/variables.less";
```

This file does not exist when using Composer (bootstrap isn't located there).

FYI, my assetic config is:

```yml
assetic:
    # ...
    assets:
       # ...
       bootstrap_submenu_css:
          inputs:
             - %kernel.root_dir%/../vendor/vsn4ik/bootstrap-submenu/less/bootstrap-submenu.less
          filters:
              - lessphp
              - cssrewrite
          output: css/bootstrap-submenu.css
       bootstrap_submenu_js:
          inputs:
             - %kernel.root_dir%/../vendor/vsn4ik/bootstrap-submenu/js/bootstrap-submenu.js
          output: js/bootstrap-submenu.js
```
